### ISSUE TITLE
Some problem about Amazon dataset 

### ISSUE THREAD

**Issue by wjlpku** [GraphSAINT/GraphSAINT#18]
Sorry to disturb you. When I download the Amazon dataset form baiduyun, I find that some nodes have no label, which means in class_map.json, some nodes' labels are all 0 in 107 dim, and the nodes num is not same with the node number described in the paper, can you check it?

**Comment by ZimpleX** [comment]
Thanks for pointing this out. 

Regarding the total number of nodes: the number listed in the paper reflects the total number of nodes in the raw data. During data preparation, we found out that a small percent of nodes are invalid (e.g., does not have node feature). So we eliminated those nodes. That's why the number of nodes in our adj is slightly less than the number of nodes listed in the paper. 

Regarding nodes without labels: this is normal and due to our preprocessing procedure. The raw data contains a lot of "rare categories" that correspond to very few nodes. Therefore, following the common practice, we eliminate those categories and keep only the most frequently occurring 107 categories. As a results, a small percent of nodes do not have any label because they do not belong to any of the 107 categories. We think this just reflects the nature of the dataset and should not be an issue w.r.t. learning. 

We have also updated `./dataset_details.md` to reflect the above clarification.

**Comment by wjlpku** [comment]
Thank you for your reply. I have one more question to ask. After I delete the unlabeled nodes and build the adjacency matrix based on the nodes with at least one label, I find that the new graph is not connected, that is, some nodes are only connected to themselves. After I remove these points and construct connected adj, I found that there are about 1000000 nodes left in the dataset. Any suggestions to how to deal with the Amazon dataset ?

**Comment by ZimpleX** [comment]
If you really want to ensure every node has a label, an alternative way may be to add an artificial category corresponding to all the categories other than the current 107 categories. Then you would have 108 node classes, and the graph structure keeps unchanged. I think some researchers also did this kind of preprocessing. 

Also, I wouldn't be surprised that removing unlabeled nodes and iteratively peeling the graph until a single connected component results in much fewer nodes. From Figure 5 of our paper, you can see that Amazon graph has more percent of low degree nodes. Those low degree nodes may also more likely be unlabelled --- These may correspond to products of "strange" categories that few customers would purchase / co-purchase. 

I think after you remove those unlabelled nodes, it may not be necessary to further remove nodes to ensure the entire graph is connected. If you add a self-edge to those isolated nodes, even the edge sampler of GraphSAINT would be able to sample the isolated nodes into the minibatches and learn their features.

**Comment by wjlpku** [comment]
Thanks for your advice, I will try, and one more question, if I remove unlabelled nodes, and there are some isolated nodes, it seems like these nodes will not benefit from the effects of GCN?

**Comment by ZimpleX** [comment]
Yes. Applying a GNN on those isolated nodes is just equivalent to applying a MLP. But the fact that they are isolated already indicates that other nodes don't correlate with them. So I think using a GNN on a graph with isolated nodes still makes sense.
