### ISSUE TITLE
question on inter-subgraph edges in node and RW sampling

### ISSUE THREAD

**Issue by abasak24** [GraphSAINT/GraphSAINT#21]
Hi, 
Can I please ask a question about the graphSAINT mechanism to clarify my understanding?
Node and RW sampling are techniques for constructing a mini-batch consisting of a specific number of nodes. These chosen/sampled nodes in the current subgraph will have edges between them. But does GraphSAINT take into account the edges between a sampled node in the current subgraph and some other node which has not been sampled in the current subgraph? For example, A-B may be an edge in the actual full graph. Let's say A in sampled in the current subgraph but B is not. Does graphSAINT do anything about this edge in the subgraph training where A is present? If not, could you please explain why it is OK to ignore these inter-subgraph edges? Thanks!

**Comment by abasak24** [comment]
May I please ask another question about comparison with Cluster-GCN? Cluster-GCN uses community structure in each subgraph to improving embedding utilization to reduce the training computation time complexity. GraphSAINT is using random node sampling or random walks which are not focused on community structure. How does GraphSAINT's training computation complexity compare to Cluster-GCN? Also, how does GraphSAINT compare to cluster-GCN in terms of memory space complexity. If you could help me understand these time and space complexities intuitively, it would be great! Thank you!

**Comment by ZimpleX** [comment]
Roughly, both should be quite similar in terms of both computation and space complexity. 

Suppose:
* GraphSAINT and Cluster-GCN compute on subgraphs of the same size (num. nodes and num. edges)
* GraphSAINT and Cluster-GCN operate on the same GNN architecture (e.g., L-layer GraphSAGE-mean)

If we ignore the pre-processing cost (which we compared in Appendix D.2 of our paper), then the computation and space complexity for each gradient update iteration are exactly the same. Of course, Cluster-GCN and GraphSAINT generate subgraphs of different sizes, and their convergence rate are also different. That's why doing exact comparison is non-trivial. Our analysis in Appendix D.2 may provide you with some useful empirical evidence. 

As for the analysis, I think the computation and space complexity calculation are exactly the same for the two methods. Essentially, after you do the analysis for the full graph, you just replace those relevant parameters with the ones for the subgraph. In fact, you can also refer to our [IEEE/IPDPS '19](https://arxiv.org/pdf/1810.11899.pdf) paper
for detailed calculation steps. In Section II, we abstract the computation into two major steps (feature aggregation and weight application), and in Section III, we explain the complexity for various minibatch methods (including GraphSAGE and GraphSAINT).

**Comment by abasak24** [comment]
Thanks again!
