### ISSUE TITLE
Intuition behind choosing hparams for train_config

### ISSUE THREAD

**Issue by omgmax** [GraphSAINT/GraphSAINT#26]
Hello,

Can you please provide some guidance and intuition for choosing appropriate hyperparameters for the train_config?

And can you give extra attention to `arch` please, thank you!

**Comment by omgmax** [comment]
Just realized there's a README in the train_config directory that explains everything very well!

**Comment by ZimpleX** [comment]
One important observation is that the subgraph size should not be too small in order to ensure reasonable connectivity within the minibatch. E.g., it may be beneficial to let the subgraph degree to be larger than 5. You can increase the subgraph degree by increasing the subgraph size (e.g., subgraphs of up to 10k-100k nodes should be doable on most GPUs). 

If the graph you are working on is really gigantic (e.g., more than 10M nodes), then you may consider some other variations of the random walk samplers that encourage better local connectivity. Not sure if this is your case.
