### ISSUE TITLE
some question about it

### ISSUE THREAD

**Issue by tanjia123456** [GraphSAINT/GraphSAINT#29]
Hello, thank you for your work.
The idea in the article is to sample the a big graph into a sub-graph. I segmented the brain. Each subject has a graph, so there are multiple graphs, and each brain area corresponds to a different label and color. How to deal with this? which code should I mainly look at?
If I have 100 pictures, I downsample it to get 100 sub-graph?

**Comment by tedzhouhk** [comment]
Hi Tanjia, thank you for your interest.

Since you said "segement", I am assuming there is no connection between each pair of subjects. Then it naturally forms unconnected "subgraphs". You can choose either use each subgraph as one iteration, or continuously samples on the subgraphs (like what we do in the PPI dataset). I am not an expert in brain imaging, but I have seen some other papers using GNN to analyze brain MRIs. Maybe you can refer to them for more help?

The core of our samplers are written in Cython (/graphsaint/cython_sampler.pyx), with a python wrapper (/graphsaint/graph_samplers.py).
