### ISSUE TITLE
confused about some details in the paper

### ISSUE THREAD

**Issue by Wjk666** [GraphSAINT/GraphSAINT#3]
Dear professor,
recently I was learning the paper of graphSaint, but I was confused about minibatch. While I refer it in your codes, I found your minibatch is divided by nodes in order!? And I wonder to know the differences between minibatch and subgraph. Do they represent the same thing ?Looking forward to your reply. Thanks so much!!
`class Minibatch:
    """
    This minibatch iterator iterates over nodes for supervised learning.
    """

    def __init__(self, adj_full, adj_full_norm, adj_train, role, class_arr, placeholders, train_params, **kwargs):
        """
        role:       array of string (length |V|)
                    storing role of the node ('tr'/'va'/'te')
        class_arr: array of float (shape |V|xf)
                    storing initial feature vectors
        """
        self.num_proc = 1
        self.node_train = np.array(role['tr'])
        self.node_val = np.array(role['va'])
        self.node_test = np.array(role['te'])

        self.class_arr = class_arr
        self.adj_full = adj_full
        self.adj_full_norm = adj_full_norm
        s1=int(adj_full_norm.shape[0]/8*1)
        s2=int(adj_full_norm.shape[0]/8*2)
        s3=int(adj_full_norm.shape[0]/8*3)
        s4=int(adj_full_norm.shape[0]/8*4)
        s5=int(adj_full_norm.shape[0]/8*5)
        s6=int(adj_full_norm.shape[0]/8*6)
        s7=int(adj_full_norm.shape[0]/8*7)
        self.dim0_adj_sub = adj_full_norm.shape[0]/8
        self.adj_full_norm_0=adj_full_norm[:s1,:]
        self.adj_full_norm_1=adj_full_norm[s1:s2,:]
        self.adj_full_norm_2=adj_full_norm[s2:s3,:]
        self.adj_full_norm_3=adj_full_norm[s3:s4,:]
        self.adj_full_norm_4=adj_full_norm[s4:s5,:]
        self.adj_full_norm_5=adj_full_norm[s5:s6,:]
        self.adj_full_norm_6=adj_full_norm[s6:s7,:]
        self.adj_full_norm_7=adj_full_norm[s7:,:]
        self.adj_train = adj_train`

**Comment by Wjk666** [comment]
Dear professor, 
    recently I was learning the paper of graphSaint, but I was confused about minibatch. While I refer it in your codes, I found your minibatch is divided by nodes in order!? And I wonder to know the differences between minibatch and subgraph. Do they represent the same thing ?Looking forward to your requests. Thanks so much!!

**Comment by GraphSAINT** [comment]
Thanks for your interest! 

First of all, one minibatch in our method is equivalent to one randomly sampled subgraph. 

Second, minibatches are sampled randomly, not divided by nodes in order. The sampling part is implemented by the `par_graph_sample` function of `minibatch.py`, which in turn invokes the sampler wrapper in `graph_samplers.py` and the underlying cython implementation `cython_sampler.pyx`. The sampled subgraphs are fed into the placeholder with keys of `adj_subgraph` and `node_subgraph`, in the `feed_dict` function. 

To address your confusion: for training, the code proceeds in the minibatch fashion, while for validation/testing, the code proceeds in the full-batch fashion. As pointed out in the last section of our `README`, full-batch evaluation is performed for GraphSAINT as well as for **all** baselines so that the comparison is fair. Note that full batch val/test evaluation is also a common setup in most of the original papers of baseline.  

Now, to perform full-batch evaluation on val/test sets, the easiest way is to feed the full-graph adj into the placeholder. However, for large graphs, this may cause GPU errors. Therefore, we divide the full-graph adj into 8 partitions so that Tensorflow won't complain that the adj is too large. Also, notice that this way of full-batch evaluation will generate classification for all the training/validation/test nodes. So in `evaluate_full_batch` function of `train.py`, we mask out the proper subsets based on the mode (whether it is val or test).

**Comment by Wjk666** [comment]
> Thanks for your interest!
> 
> First of all, one minibatch in our method is equivalent to one randomly sampled subgraph.
> 
> Second, minibatches are sampled randomly, not divided by nodes in order. The sampling part is implemented by the `par_graph_sample` function of `minibatch.py`, which in turn invokes the sampler wrapper in `graph_samplers.py` and the underlying cython implementation `cython_sampler.pyx`. The sampled subgraphs are fed into the placeholder with keys of `adj_subgraph` and `node_subgraph`, in the `feed_dict` function.
> 
> To address your confusion: for training, the code proceeds in the minibatch fashion, while for validation/testing, the code proceeds in the full-batch fashion. As pointed out in the last section of our `README`, full-batch evaluation is performed for GraphSAINT as well as for **all** baselines so that the comparison is fair. Note that full batch val/test evaluation is also a common setup in most of the original papers of baseline.
> 
> Now, to perform full-batch evaluation on val/test sets, the easiest way is to feed the full-graph adj into the placeholder. However, for large graphs, this may cause GPU errors. Therefore, we divide the full-graph adj into 8 partitions so that Tensorflow won't complain that the adj is too large. Also, notice that this way of full-batch evaluation will generate classification for all the training/validation/test nodes. So in `evaluate_full_batch` function of `train.py`, we mask out the proper subsets based on the mode (whether it is val or test).

Thanks for your explanation ! And I want to check my understanding about the paper and method!
First,in your Algotrithm1 of the paper, sampling subgraph was done in each minibatch. So I misunderstood that it need lots of subgraphs in each minibatch. All in all, one subgraph was done in one minibatch. And at the same time, this subgraph was used to correct the parameters. Is that true?But I was also confusedd about that when we are sampling subgraph per minibatch, it will lose some edges in the whole graph by masking them in Adjacency matrix. What we can do is maintaining some important information. And those lost information will also be ignored in the val/test process. Am I correct?(I was a greenhand and Sophomore student, So the question I asked may be simpler.Thanks for your explanation again)
Second, May you talk about the reasons why graphSaint is so excellent? why sampling firstly and running full GCN coud produce such pretty results?Is Because its outstanding sampling method?
Thirdly, I met some error when running your code...could you help me ?
 `(F:\Anaconda\envs\py3) E:\机器学习之路\图卷积\代码\GraphSAINT-master>python -m graphsaint.train --data_prefix ./data/ppi --train_config ./train_config/table2/ppi2_rw.yml
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
'nvidia-smi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
E:\机器学习之路\图卷积\代码\GraphSAINT-master\graphsaint\utils.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  train_config = yaml.load(f_train_config)
Loading training data..
Done loading training data..
>> layer highorderaggregator_1, dim: [50,512]
>> layer highorderaggregator_2, dim: [1024,512]
>> layer highorderaggregator_3, dim: [512,512]
>> layer highorderaggregator_4, dim: [1024,512]
2019-10-28 08:54:46.474814: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-10-28 08:54:46.817147: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-10-28 08:54:46.825511: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: DESKTOP-E9J61K2
2019-10-28 08:54:46.826291: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: DESKTOP-E9J61K2
Traceback (most recent call last):
  File "F:\Anaconda\envs\py3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Anaconda\envs\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\机器学习之路\图卷积\代码\GraphSAINT-master\graphsaint\train.py", line 254, in <module>
    tf.app.run(main=train_main)
  File "F:\Anaconda\envs\py3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "E:\机器学习之路\图卷积\代码\GraphSAINT-master\graphsaint\train.py", line 248, in train_main
    model,minibatch,sess,train_stat,ph_misc_stat,summary_writer = prepare(train_data,train_params,arch_gcn)
  File "E:\机器学习之路\图卷积\代码\GraphSAINT-master\graphsaint\train.py", line 121, in prepare
    summary_writer = tf.summary.FileWriter(log_dir(FLAGS.train_config,FLAGS.data_prefix,git_branch,git_rev,timestamp), sess.graph)
  File "E:\机器学习之路\图卷积\代码\GraphSAINT-master\graphsaint\utils.py", line 103, in log_dir
    os.makedirs(log_dir)
  File "F:\Anaconda\envs\py3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './tf_log/ppi/2019-10-28 08:54:40-graphsaint-/'`

**Comment by GraphSAINT** [comment]
For your questions:

1. Yes, only one subgraph is used per minibatch. And we sample many subgraphs to estimate the coefficients, as a pre-processing step. Maybe it's better to discuss an example: Let's assume we have a graph with 1000 training nodes in total, and the sampler will always return a 100-node subgraph. Now according to the setup in the paper, if N=50 (N defined in Sec 3.2), then the pre-processing step will sample (and also store) 1000/100*50=500 subgraphs to estimate the normalization coefficients. The actual training will start after pre-processing finishes. For the first 500 minibatches, we don't need to sample new subgraphs, since we can just take the already sampled ones during pre-processing. If training does not converge within 500 minibatches, then for each minibatch beyond 500, we need to freshly sample a new subgraph. 

2. If we consider one minibatch,  then some edge information will be lost due to graph sampling. However, if we consider the training process as a whole, the hope is the lost information will eventually be recovered by the many subgraphs sampled. Say a node A has neighbors B,C,D in the original graph. Then one subgraph may contain edges (A,B), (A,C) and lose (A,D). However, the other subgraph may contain edges (A,C) and (A,D). Since the two subgraphs update the same GCN weights, then all information of neighbors B,C,D could be learnt in a way. For val/test evaluation, since no sampling is performed, then you can say no edge information is lost. 

3. For comparison of GraphSAINT with other methods, you can refer to the paragraph in Section 4. In addition, we also feel that the constant neighbor size help address the smoothening effect caused by neighbor explosion. The normalization and designed sampler indeed help with accuracy improvement. 

For the error you encountered:

Reasons:

1. When logging the training stats, we record the git revision number to make book-keeping easier. So lines 9-10 of `globals.py` automatically grab the git revision number. It seems that your GraphSAINT does not contain a `.git` folder. We suggest you copy our code by `git clone` to avoid such issue.

2. Are you using NVIDIA GPUs? If so, you can avoid the error by installing `nvidia-smi`. If you prefer to train on CPU, you can comment out lines 51-73 in `globals.py` so that our code will not try to locate an idle GPU using `nvidia-smi`.

**Comment by Wjk666** [comment]
I am very grateful for your detailed explaination! I have gradually understand your paper in the correct way!  By the way, I am looking forward to your good news  in the receiving results of ICLR2020! Thanks a lot again!

**Comment by GraphSAINT** [comment]
Thanks for your wishes! We are more than happy to help!
