### ISSUE TITLE
Question about aggregation in backprop

### ISSUE THREAD

**Issue by chenxuhao** [GraphSAINT/GraphSAINT#31]
Hello,
I notice that in the backprop, the GCN layer does two aggregations:
https://github.com/GraphSAINT/GraphSAINT/blob/93b508ec1ea027b1c7c8b611254c0508510fca22/ipdps19_cpp/layer.cpp#L137
https://github.com/GraphSAINT/GraphSAINT/blob/93b508ec1ea027b1c7c8b611254c0508510fca22/ipdps19_cpp/layer.cpp#L132

this is in the case that 
if (dim_weight_in >= dim_weight_out/2) and
if (id_layer > 0)

so for the second GCN layer (id=1), since dim_in and dim_out are both dim_hid, so dim_in > dim_out, in this case, the sparseMM is computed twice, which is not necessary to my understanding. Am I missing anything?

Meanwhile, in the case of (dim_weight_in < dim_weight_out/2) and (id_layer > 0), line 137 to 139 don't compute the gredients for line 97&98 in the forward phase.

Thank you!

Best,
Xuhao

**Comment by ZimpleX** [comment]
Hi Xuhao,

Great suggestions! I've checked that both are valid points, and have pushed a fix just now. I've also changed the naming from GCN to SAGE, since the architecture is GraphSAGE to be more precise. 

Just in case, the codes may be better explained by our [journal version](https://www.sciencedirect.com/science/article/pii/S0743731520303579). The operations in `backward` correspond to Eq. 12 and the two orders of computation correspond to Sec 6.1. 

I now use the flag of `is_order_AX_W` to mark the computation order for a layer, since such an order should be consistent for both forward and backward pass (otherwise we cannot use `feat_aggr` to store the intermediate result during backprop due to array size mismatch). 

I tested both orders on Reddit and it seems to be correct. Please let me know if you encounter any issues. 

Thanks,
Hanqing
