### ISSUE TITLE
Questions about alpha and lambda

### ISSUE THREAD

**Issue by lt610** [GraphSAINT/GraphSAINT#34]
Hello,
I'm confused about the approximate calculation of alpha and lambda in paper. Why can we set $\alpha_{u,v} = C_{u,v} / C_v$ and $\lambda_v = C_v / N$?
Thanks.

**Comment by ZimpleX** [comment]
Both are just the Monte Carlo method for estimating the edge and node probability. 

By definition of alpha, it is the probability of sampling edge u,v conditioned on v being sampled. Therefore, if a node v is sampled C_v times (i.e., v appears in C_v subgraphs), and the edge u,v is sampled C_{u,v} times (i.e., u,v appears in C_{u,v} subgraphs), then C_{u,v} / C_v can estimate the conditional edge probability. 

By definition of lambda, it is the probability of v being sampled in one subgraph. So if we sample a total of N subgraphs, and v appears C_v times, then C_v / N estimates the node probability. 

Since we want to apply the normalization for arbitrary sampling algorithm, we go for such a numerical method for estimating the node and edge probabilities. Similar to all Monte Carlo methods, the more subgraphs we sample (i.e., the higher N is), the more accurate we can estimate alpha and lambda.

**Comment by lt610** [comment]
Thank you for your reply. In paper $\lambda_v = |V| \times P_v$, if $P_v = C_v / N$ then $ \lambda_v = |V| \times C_v / N$. I am confused about the disappearance of |V|.

**Comment by ZimpleX** [comment]
Please check this line in `minibatch.py`:

https://github.com/GraphSAINT/GraphSAINT/blob/6126102d8746ad35521737f6ffd1d4ff1ef03fcf/graphsaint/pytorch_version/minibatch.py#L210

Here we are directly calculating 1 / lambda, which is N / C_v / |V|. Afterwards, in the minibatch loss computation, we perform weighted sum on the loss per subgraph node, with 1 / lambda as the weight:

https://github.com/GraphSAINT/GraphSAINT/blob/6126102d8746ad35521737f6ffd1d4ff1ef03fcf/graphsaint/pytorch_version/models.py#L125-L130

**Comment by lt610** [comment]
I get it. Thanks.
