### ISSUE TITLE
Dataset Amazon and the description do not match. 

### ISSUE THREAD

**Issue by xrrain** [GraphSAINT/GraphSAINT#36]
As the title, we found the batch size of Graphsage has great influence over the performance on Amazon dataset as the Table 11 shows in your paper. However, we found the dataset Amazon we download from the Google Driver has 1,569,960 nodes and 96,295 nodes  have no labels, which is incompatible with the description in your paper for the dataset. 
* Is there any extra process to deal with the Amazon Dataset? 
* And can you kindly provide any explanations about the performance trend ( increase then decrease when batch size increase for GraphSage over Amazon)?

**Comment by ZimpleX** [comment]
Regarding the Amazon dataset: please refer to issue #18 for the detailed explanation. 

Regarding the accuracy change for GraphSAGE: 

Firstly, since GraphSAGE performs neighbor sampling for each target node independently, the effect of changing batch size in GraphSAGE is in a way similar to the effect of changing batch size in other non-GNN deep learning models. So a well-known result is that, an overly large batch size may lead to poor generalization. 

Secondly, I suspect this is due to the skewed degree distribution of the Amazon graph. Looking at Fig 5, Amazon contains some extremely high degree nodes. When we have a large batch size, the neighbor sampling would almost always include those high degree nodes in the neighborhood. In other words, the features of those nodes may influence every iteration of the gradient update. This may make it challenging to learn the features of those low-degree, not-so-well-connected nodes. However, when calculating the accuracy, each node contribute equally, regardless of their connectivity. 

GraphSAINT may be able to address such an issue with our proposed sampler. For example, in the Edge sampler, we actually set higher probability to those edges of low degree nodes. Also, even though the subgraph size of GraphSAINT is much larger than the batch size of GraphSAGE, the total number of nodes involved in GraphSAGE in each gradient update is much larger than that of GraphSAINT. For GraphSAGE with batch size 2k, and the sampling budget of 10, the total number of nodes involved (i.e., the neighborhood size) can be as large as 200k.
