### ISSUE TITLE
some question about sampling

### ISSUE THREAD

**Issue by Wjk666** [GraphSAINT/GraphSAINT#6]
Hey bro, it;s me again ! You good? 
    Recently I was reading some paper about graph sampling. And I remember your team has used excellent graph sampling methods in this paper! So I want to matter your team to  help me again!
1 The most important issue is that how to use random walk based samplers. Because the target of using method of random walk is to obtain several sequences made up of vertices which could preserve the properties of the original graph. But how could you form those sequences to into a subgtaph? just focus on some special vertices and use random walk repreatly on them to construct a subgraph?
2 What do you think of the effect of regular random walk and multi-dimensional random walk sampler defined in Ribeiro&Towsley(2010).In terms of experimental results, This two  the performance of the two models is similar.
3 If I want to use your sampling result, but I prefer to obtain several random walk sequences rather them the complete subgraph. Could you give me some advice?
Thank you so much !! And sorry to bother you again!

**Comment by GraphSAINT** [comment]
Nice to hearing from you!

1. The sampling algorithms (including the RW sampler) are specified in Appendix B of the paper. In particular, for RW, we don't really constrain ourselves to "special vertices". In fact, we don't have any notion of "speciality" in the RW algorithm. We just uniformly at random choose nodes as the roots, and uniformly at random expand one neighbor at a time during the walk. Although simple, GraphSAINT can still effectively learn from such sampling process, due to the normalization discussed in Section 3. It is true that the sampling may end up with a bunch of isolated paths as the minibatch subgraph. In this case, you may wonder how can GraphSAINT learn properly since the subgraph loses so many neighbors. Well, to understand this, note that the training process learns from the numerous subgraph altogether. So neighbors lost in one subgraph will eventually be picked up by other subgraphs. Overall, considering all the subgraphs as a whole, you don't lose much information for the GCN model. 

2. MRW and RW indeed give similar accuracy. However, convergence of MRW is slightly slower than RW. We think there may be the following reasons: RW sampler results in lower variance than MRW; or, MRW sampler results in too unbalanced node/edge sampling probability.

3. If I understand it correctly, you don't want the induction step after the random walks. You have two options to achieve this: 

a). Modify `graphsaint/cython_sampler.pyx`. First of all, you need to comment out lines 332 and 333 so that the order of node indices in`self.node_sampled` corresponds to the order of nodes touched in the random walk. Then you need to modify `par_sample` function from line 182 so that the `self.node_sampled` array is returned (E.g., comment out line 187). Then once cython returns the RW sequence, the `graphsaint/graph_samplers.py` need to construct adj based on just the RW sequences. I haven't yet tested it, but it seems that this should work. This option may take some time, since cython is not as handy as python.

b). If you don't mind the sampler to be slow, you can simply create a new class in `graphsaint/graph_samplers.py`. Then you just implement the standard RW in pure python. You basically need to overwrite the `par_sample` function defined in the super-class. Be careful about the return values of the new `par_sample` function, though.

**Comment by Wjk666** [comment]
Thank you for your detailed reply . I think I should go over your paper and codes again. It seem that I have some thoughts about how to implement it. Of course,  thanks a lot for your patience and help!!!

**Comment by GraphSAINT** [comment]
No problem at all! We sincerely wish to make our work useful to the community.
