### ISSUE TITLE
Test set F1-micro score of Cluster-GCN on Reddit

### ISSUE THREAD

**Issue by wjlpku** [GraphSAINT/GraphSAINT#7]
Hi, sorry to disturb you.
I have questions about f1 score of Reddit dataset.
I notice in your paper,  in table 3, f1 score of cluster-gcn 4x128 is 99.66,
However, I can not reproduce experimental accuracy from Open-sourced implementation in google-research, in my experiment, the best micro-F1 score of cluster-gcn is 99.63.
I wonder how you achieve 99.66 using cluster-gcn in Reddit ?

**Comment by GraphSAINT** [comment]
Is there a typo? Did you mean to say 96.6 and 96.3?

**Comment by wjlpku** [comment]
In paper "cluster-gcn", it does report the testing accuracy of Reddit is 96.6, however, I can not reproduce this result by their open-source code, I wonder whether you have test 4X128 cluster-gcn experiment and get the 96.6?
And hope you give me some advice about it.

**Comment by GraphSAINT** [comment]
Since this is more of a question on Cluster-GCN, maybe you could try contacting the authors of Cluster-GCN for an official reply?

On the other hand, we are willing to share with you the details. However, out of respect for the work of Cluster-GCN, we think it may be more appropriate to keep this conversion privately so that others won't be biased by our "unofficial" experiment setting. 

Could you let us know your email or send a message to us at GraphSAINTKDD19@gmail.com?

**Comment by wjlpku** [comment]
Sure, thanks for your advice
